spring:
  datasource:
    url: jdbc:mysql://localhost:3330/skill_up?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  port: 8081
